# Generated by Django 5.2.4 on 2025-07-27 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="updates_at",
            new_name="updated_at",
        ),
    ]
